package modelo;
// Generated 22/04/2016 02:45:34 PM by Hibernate Tools 4.3.1



/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int idAlumno;
     private String ANombre;
     private String AContrasenha;
     private String ACorreo;

    public Alumno() {
    }

	
    public Alumno(int idAlumno, String AContrasenha, String ACorreo) {
        this.idAlumno = idAlumno;
        this.AContrasenha = AContrasenha;
        this.ACorreo = ACorreo;
    }
    public Alumno( String ANombre, String AContrasenha, String ACorreo) {
     
       this.ANombre = ANombre;
       this.AContrasenha = AContrasenha;
       this.ACorreo = ACorreo;
    }
    public Alumno(int idAlumno, String ANombre, String AContrasenha, String ACorreo) {
       this.idAlumno = idAlumno;
       this.ANombre = ANombre;
       this.AContrasenha = AContrasenha;
       this.ACorreo = ACorreo;
    }
   
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public String getANombre() {
        return this.ANombre;
    }
    
    public void setANombre(String ANombre) {
        this.ANombre = ANombre;
    }
    public String getAContrasenha() {
        return this.AContrasenha;
    }
    
    public void setAContrasenha(String AContrasenha) {
        this.AContrasenha = AContrasenha;
    }
    public String getACorreo() {
        return this.ACorreo;
    }
    
    public void setACorreo(String ACorreo) {
        this.ACorreo = ACorreo;
    }




}


