package modelo.sql;
// Generated 19/04/2016 11:53:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private int idActividad;
     private Area area;
     private Profesor profesor;
     private Tipo tipo;
     private int ICupodisponible;
     private int ICupomaximo;
     private String SNombre;
     private String SDescripciom;
     private Date FFechamodificacion;
     private Date FFechadescripion;
     private Set<ActividadAlumno> actividadAlumnos = new HashSet<ActividadAlumno>(0);
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

    public Actividad() {
    }

	
    public Actividad(int idActividad, Area area, Profesor profesor, Tipo tipo, int ICupodisponible, int ICupomaximo, String SNombre, String SDescripciom, Date FFechamodificacion, Date FFechadescripion) {
        this.idActividad = idActividad;
        this.area = area;
        this.profesor = profesor;
        this.tipo = tipo;
        this.ICupodisponible = ICupodisponible;
        this.ICupomaximo = ICupomaximo;
        this.SNombre = SNombre;
        this.SDescripciom = SDescripciom;
        this.FFechamodificacion = FFechamodificacion;
        this.FFechadescripion = FFechadescripion;
    }
    public Actividad(int idActividad, Area area, Profesor profesor, Tipo tipo, int ICupodisponible, int ICupomaximo, String SNombre, String SDescripciom, Date FFechamodificacion, Date FFechadescripion, Set<ActividadAlumno> actividadAlumnos, Set<Solicitud> solicituds) {
       this.idActividad = idActividad;
       this.area = area;
       this.profesor = profesor;
       this.tipo = tipo;
       this.ICupodisponible = ICupodisponible;
       this.ICupomaximo = ICupomaximo;
       this.SNombre = SNombre;
       this.SDescripciom = SDescripciom;
       this.FFechamodificacion = FFechamodificacion;
       this.FFechadescripion = FFechadescripion;
       this.actividadAlumnos = actividadAlumnos;
       this.solicituds = solicituds;
    }
   
    public int getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(int idActividad) {
        this.idActividad = idActividad;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public int getICupodisponible() {
        return this.ICupodisponible;
    }
    
    public void setICupodisponible(int ICupodisponible) {
        this.ICupodisponible = ICupodisponible;
    }
    public int getICupomaximo() {
        return this.ICupomaximo;
    }
    
    public void setICupomaximo(int ICupomaximo) {
        this.ICupomaximo = ICupomaximo;
    }
    public String getSNombre() {
        return this.SNombre;
    }
    
    public void setSNombre(String SNombre) {
        this.SNombre = SNombre;
    }
    public String getSDescripciom() {
        return this.SDescripciom;
    }
    
    public void setSDescripciom(String SDescripciom) {
        this.SDescripciom = SDescripciom;
    }
    public Date getFFechamodificacion() {
        return this.FFechamodificacion;
    }
    
    public void setFFechamodificacion(Date FFechamodificacion) {
        this.FFechamodificacion = FFechamodificacion;
    }
    public Date getFFechadescripion() {
        return this.FFechadescripion;
    }
    
    public void setFFechadescripion(Date FFechadescripion) {
        this.FFechadescripion = FFechadescripion;
    }
    public Set<ActividadAlumno> getActividadAlumnos() {
        return this.actividadAlumnos;
    }
    
    public void setActividadAlumnos(Set<ActividadAlumno> actividadAlumnos) {
        this.actividadAlumnos = actividadAlumnos;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }




}


