package modelo.sql;
// Generated 19/04/2016 11:53:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ActividadAlumno generated by hbm2java
 */
public class ActividadAlumno  implements java.io.Serializable {


     private int idActividadAlumno;
     private Actividad actividad;
     private Alumno alumno;
     private Date FFechainicio;
     private Date FFechafin;
     private int BTerminada;

    public ActividadAlumno() {
    }

    public ActividadAlumno(int idActividadAlumno, Actividad actividad, Alumno alumno, Date FFechainicio, Date FFechafin, int BTerminada) {
       this.idActividadAlumno = idActividadAlumno;
       this.actividad = actividad;
       this.alumno = alumno;
       this.FFechainicio = FFechainicio;
       this.FFechafin = FFechafin;
       this.BTerminada = BTerminada;
    }
   
    public int getIdActividadAlumno() {
        return this.idActividadAlumno;
    }
    
    public void setIdActividadAlumno(int idActividadAlumno) {
        this.idActividadAlumno = idActividadAlumno;
    }
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Date getFFechainicio() {
        return this.FFechainicio;
    }
    
    public void setFFechainicio(Date FFechainicio) {
        this.FFechainicio = FFechainicio;
    }
    public Date getFFechafin() {
        return this.FFechafin;
    }
    
    public void setFFechafin(Date FFechafin) {
        this.FFechafin = FFechafin;
    }
    public int getBTerminada() {
        return this.BTerminada;
    }
    
    public void setBTerminada(int BTerminada) {
        this.BTerminada = BTerminada;
    }




}


