package modelo.sql;
// Generated 19/04/2016 11:53:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int idAlumno;
     private int NNumerocuenta;
     private String SNombre;
     private String SAppaterno;
     private String SApmaterno;
     private String SContrasenha;
     private String SCorreo;
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
     private Set<ActividadAlumno> actividadAlumnos = new HashSet<ActividadAlumno>(0);

    public Alumno() {
    }

	
    public Alumno(int idAlumno, int NNumerocuenta, String SNombre, String SAppaterno, String SApmaterno, String SContrasenha, String SCorreo) {
        this.idAlumno = idAlumno;
        this.NNumerocuenta = NNumerocuenta;
        this.SNombre = SNombre;
        this.SAppaterno = SAppaterno;
        this.SApmaterno = SApmaterno;
        this.SContrasenha = SContrasenha;
        this.SCorreo = SCorreo;
    }
    public Alumno(int idAlumno, int NNumerocuenta, String SNombre, String SAppaterno, String SApmaterno, String SContrasenha, String SCorreo, Set<Solicitud> solicituds, Set<ActividadAlumno> actividadAlumnos) {
       this.idAlumno = idAlumno;
       this.NNumerocuenta = NNumerocuenta;
       this.SNombre = SNombre;
       this.SAppaterno = SAppaterno;
       this.SApmaterno = SApmaterno;
       this.SContrasenha = SContrasenha;
       this.SCorreo = SCorreo;
       this.solicituds = solicituds;
       this.actividadAlumnos = actividadAlumnos;
    }
   
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public int getNNumerocuenta() {
        return this.NNumerocuenta;
    }
    
    public void setNNumerocuenta(int NNumerocuenta) {
        this.NNumerocuenta = NNumerocuenta;
    }
    public String getSNombre() {
        return this.SNombre;
    }
    
    public void setSNombre(String SNombre) {
        this.SNombre = SNombre;
    }
    public String getSAppaterno() {
        return this.SAppaterno;
    }
    
    public void setSAppaterno(String SAppaterno) {
        this.SAppaterno = SAppaterno;
    }
    public String getSApmaterno() {
        return this.SApmaterno;
    }
    
    public void setSApmaterno(String SApmaterno) {
        this.SApmaterno = SApmaterno;
    }
    public String getSContrasenha() {
        return this.SContrasenha;
    }
    
    public void setSContrasenha(String SContrasenha) {
        this.SContrasenha = SContrasenha;
    }
    public String getSCorreo() {
        return this.SCorreo;
    }
    
    public void setSCorreo(String SCorreo) {
        this.SCorreo = SCorreo;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }
    public Set<ActividadAlumno> getActividadAlumnos() {
        return this.actividadAlumnos;
    }
    
    public void setActividadAlumnos(Set<ActividadAlumno> actividadAlumnos) {
        this.actividadAlumnos = actividadAlumnos;
    }




}


