package modelo.sql;
// Generated 19/04/2016 11:53:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private int idSolicitud;
     private Actividad actividad;
     private Alumno alumno;
     private Profesor profesor;
     private Date FFechaenvio;
     private int BAceptada;

    public Solicitud() {
    }

    public Solicitud(int idSolicitud, Actividad actividad, Alumno alumno, Profesor profesor, Date FFechaenvio, int BAceptada) {
       this.idSolicitud = idSolicitud;
       this.actividad = actividad;
       this.alumno = alumno;
       this.profesor = profesor;
       this.FFechaenvio = FFechaenvio;
       this.BAceptada = BAceptada;
    }
   
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public Date getFFechaenvio() {
        return this.FFechaenvio;
    }
    
    public void setFFechaenvio(Date FFechaenvio) {
        this.FFechaenvio = FFechaenvio;
    }
    public int getBAceptada() {
        return this.BAceptada;
    }
    
    public void setBAceptada(int BAceptada) {
        this.BAceptada = BAceptada;
    }




}


